name: Cleanup
on:
  workflow_run:
    workflows: ["Test Dev"]
    types:
      - completed
jobs:
  Cleanup:
    runs-on: [self-hosted, dev]
    steps:
      - name: Delete Container
        run: |
          docker rm -f current-container || true