services:
  builder:
    build: ./builder
    volumes:
      - public:/public
      - ./builder/src:/src
    networks:
      - default
  certbot:
    build: ./certbot
    volumes:
      - letsencrypt:/letsencrypt
      - certs:/etc/letsencrypt
      - cmd:/cmd
      - nginx-configs:/config
    environment:
      - PUBLIC_DIR=/usr/share/nginx/html
      - LETS_ENCRYPT_DIR=/letsencrypt/
    stdin_open: true
    tty: true
    networks:
      - default
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - certs:/etc/letsencrypt
      - cmd:/cmd
      - public:/usr/share/nginx/html:ro
      - nginx-configs:/etc/nginx/conf.d
    environment:
      - PUBLIC_DIR=/usr/share/nginx/html
      - LETS_ENCRYPT_DIR=/letsencrypt/
    networks:
      - default
  bash:
    build: ./bash
    volumes:
      - letsencrypt:/letsencrypt
      - certs:/certs
      - cmd:/cmd
      - public:/public
      - nginx-configs:/nginx-configs
    networks:
      - default
volumes:
  letsencrypt:
  certs:
  cmd:
  public:
  nginx-configs:
networks:
  default: