name: Build Bash
on:
  push:
    branches:
      - bash-config
jobs:
  build-bash:
    runs-on: [self-hosted, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: bash-config
      - name: Build
        working-directory: ./ClientServer
        run: |
          sudo docker compose stop bash || true
          sudo docker compose rm -f -s bash || true
          sudo docker image rm clientserver-bash || true
          sudo docker compose create bash
          sudo docker image ls
          sudo docker ps -a
          
        