name: Run Builder
on:
  push:
    branches:
      - builder
jobs:
  run-builder:
    runs-on: [self-hosted, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: builder
      - name: Run
        working-directory: ./ClientServer
        run: |
          sudo docker compose restart builder

        
