name: CICD Dev
on:
  push:
    branches:
      - dev
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        working-directory: ./ClientServer
        run: |
          npm install --include=dev
      - name: Run Unit Tests
        working-directory: ./ClientServer
        run: |
          npm run unit-tests
      - name: Webpack Bundling
        working-directory: ./ClientServer
        run: |
          npm run build
      - name: Docker Login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build
        run: |
          docker build -t mmullin12/pong -f ./ClientServer/DockerFile ./ClientServer
      - name: Docker Push
        run: |
          docker push mmullin12/pong
  deploy:
    runs-on: [self-hosted, dev]
    steps:
      - name: Docker Login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Pull Docker Image
        run: |
          sudo docker pull mmullin12/pong:latest
      - name: Delete Old Container
        run: |
          sudo docker rm -f current-container || true
      - name: Run Container
        run: |
          sudo docker run -d -p 8080:8080 --name current-container mmullin12/pong
          sudo docker ps
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ClientServer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install --include=dev
      - name: Run End to End Tests
        run: |
          npm run e2e-tests