name: CICD Dev
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: [self-hosted, dev]
    steps:
      - name: Verify Docker
        run: |
          sudo docker run hello-world
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Dependencies
        working-directory: ./ClientServer
        run: |
          npm install --include=dev
      - name: Run Unit Tests
        working-directory: ./ClientServer
        run: |
          npm run unit-tests
      - name: Webpack Bundling
        working-directory: ./ClientServer
        run: |
          npm run build
      - name: Docker Build
        run: |
          docker build -t clientServerImage -f ./ClientServer/app.DockerFile ./ClientServer
      - name: Delete Old Docker Container
        run: |
          sudo docker rm -f current-container || true
      - name: Run Docker Container
        run: |
          sudo docker run -d -p 80:8080 --name current-container clientServerImage
          sudo docker ps
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ClientServer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      - name: Install Dependencies
        run: |
          npm install --include=dev
      - name: Run End to End Tests
        run: |
          curl http://3.22.66.44/ -o ./tests/end-to-end/htmlOutput.txt
          npm run e2e-tests