name: Test Dev
on:
  workflow_run:
    workflows: ["Deploy Dev"]
    types:
      - completed
jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ClientServer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install --include=dev
      - name: Run End to End Tests
        run: |
          npm run e2e-tests