
name: Run Containers
on:
  push:
    branches:
      - config
jobs:
  run-containers:
    runs-on: [self-hosted, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: config
      - name: Build
        working-directory: ./ClientServer
        run: |
          echo $PWD
          sudo docker compose down --remove-orphans
          sudo docker ps -a
          sudo docker images ls