name: Configure Server
on:
  push:
    branches:
      - config
jobs:
  build:
    runs-on: [self-hosted, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: config
      - name: Configure Secrets
        working-directory: ./ClientServer
        env:
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
          PUBLIC_DOMAIN: ${{ secrets.PUBLIC_DOMAIN }}
        run: |
          echo "$PUBLIC_IP" > ./public_ip.txt
          echo "$PUBLIC_DOMAIN" > ./public_domain.txt
      - name: Compose
        working-directory: ./ClientServer
        run: |
          sudo docker compose down --remove-orphans
          sudo docker compose up --build
          sudo docker system prune -a -f
          sudo docker volume ls
          sudo docker ps -a
          sudo docker image ls


        