name: Deploy Dev
on:
  workflow_run:
    workflows: [Build Client Server]
    types:
      - completed
jobs:
  Deploy:
    runs-on: [self-hosted, dev]
    steps:
      - name: Docker Login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Pull Docker Image
        run: |
          sudo docker pull mmullin12/pong:latest
      - name: Delete Old Container
        run: |
          sudo docker rm -f current-container || true
      - name: Run Container
        run: |
          sudo docker run -d -p 8080:8080 --name current-container mmullin12/pong