name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-nginx:
    runs-on: [self-hosted, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Compose
        working-directory: ./ClientServer
        run: |
          sudo docker compose down --remove-orphans
          sudo docker compose up -d --build
          sudo docker system prune -a -f
          sudo docker volume ls
          sudo docker ps -a
          sudo docker image ls


        