name: Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  build-nginx:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Compose
        working-directory: ./ClientServer
        run: |
          sudo docker compose down --remove-orphans
          sudo docker compose up -d --build
          sudo docker system prune -a -f
          sudo docker volume ls
          sudo docker ps -a
          sudo docker image ls

