name: Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: front-end
      - name: Run Tests
        working-directory: ./ClientServer/builder
        run: |
          npm install --include=dev
          npm run test
  compose-dev:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Compose
        working-directory: ./ClientServer
        run: |
          sudo docker compose down --remove-orphans
          sudo docker compose up -d --build builder
          sudo docker compose up -d --build nginx
          sudo docker compose up -d --build bash
          sudo docker system prune -a -f
          sudo docker volume ls
          sudo docker ps -a
          sudo docker image ls
