name: Rebuild Front End
on:
  push:
    branches:
      - front-end
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: front-end
      - name: Run Tests
        working-directory: ./ClientServer/builder
        run: |
          npm install --include=dev
          npm run test
  build-and-run-builder:
    runs-on: [self-hosted, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: front-end
      - name: Compose
        working-directory: ./ClientServer
        run: |
          sudo docker compose down --remove-orphans builder
          sudo docker compose up --build builder
          sudo docker system prune -a -f
          sudo docker volume ls
          sudo docker ps -a
          sudo docker image ls