name: Staging
on:
  push:
    branches:
      - staging
jobs:
  test:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging
      - name: Build
        working-directory: ./ClientServer
        run: |
          docker compose up