name: Tests
on:
  push:
    branches:
      - tests
jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'test'
      - name: Install Dependencies
        working-directory: ./ClientServer
        run: |
          npm install --include=dev
      - name: Run End to End Tests
        working-directory: ./ClientServer
        run: |
          curl http://3.22.66.44/ -o ./tests/end-to-end/htmlOutput.txt
          npm run e2e-tests -- http://3.22.66.44/