name: Run Test
on:
  push:
    branches:
      - nginx-config
      - test
jobs:
  build:
    runs-on: [self-hosted, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: test
      - name: Build
        working-directory: ./ClientServer
        run: |
          sudo docker compose stop test || true
          sudo docker compose rm -f -s test || true
          sudo docker image rm clientserver-test || true
          sudo docker compose create --build test
          sudo docker image ls
          sudo docker ps -a
          
        